from __future__ import annotations

FILES: dict[str, str] = {
"mini-commerce/backend/src/main/java/com/example/minicommerce/messaging/infrastructure/OutboxEventEntity.java": r'''package com.example.minicommerce.messaging.infrastructure;
import jakarta.persistence.*;import java.time.Instant;import java.util.UUID;
@Entity @Table(name="outbox_events",indexes=@Index(name="ix_outbox_pending",columnList="status,next_attempt_at,created_at"))
public class OutboxEventEntity{@Id@Column(name="event_id")private UUID eventId;@Column(name="aggregate_type",nullable=false,length=80)private String aggregateType;@Column(name="aggregate_id",nullable=false,length=100)private String aggregateId;@Column(name="event_type",nullable=false,length=100)private String eventType;@Column(name="schema_version",nullable=false)private int schemaVersion;@Column(nullable=false,columnDefinition="text")private String payload;@Column(nullable=false,length=20)private String status;@Column(name="attempt_count",nullable=false)private int attemptCount;@Column(name="next_attempt_at",nullable=false)private Instant nextAttemptAt;@Column(name="locked_by",length=100)private String lockedBy;@Column(name="locked_until")private Instant lockedUntil;@Column(name="last_error",length=1000)private String lastError;@Column(name="created_at",nullable=false)private Instant createdAt;@Column(name="published_at")private Instant publishedAt;protected OutboxEventEntity(){}public OutboxEventEntity(UUID id,String at,String ai,String et,String payload,Instant now){eventId=id;aggregateType=at;aggregateId=ai;eventType=et;schemaVersion=1;this.payload=payload;status="PENDING";nextAttemptAt=now;createdAt=now;}public UUID getEventId(){return eventId;}}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/messaging/infrastructure/OutboxEventRepository.java": r'''package com.example.minicommerce.messaging.infrastructure;import java.util.UUID;import org.springframework.data.jpa.repository.JpaRepository;public interface OutboxEventRepository extends JpaRepository<OutboxEventEntity,UUID>{}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/messaging/application/EventEnvelope.java": r'''package com.example.minicommerce.messaging.application;
import com.fasterxml.jackson.databind.JsonNode;import java.time.Instant;import java.util.UUID;
/** 消息是跨时间 API，因此显式携带 eventId、schemaVersion、发生时间、聚合标识和 traceId。 */
public record EventEnvelope(UUID eventId,String eventType,int schemaVersion,Instant occurredAt,String producer,String aggregateType,String aggregateId,String traceId,JsonNode payload){}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/messaging/application/OutboxService.java": r'''package com.example.minicommerce.messaging.application;
import com.example.minicommerce.messaging.infrastructure.*;import com.fasterxml.jackson.databind.*;import java.time.Clock;import java.util.*;import org.slf4j.MDC;import org.springframework.stereotype.Service;
/**
 * 业务表与待发布事件在同一 PostgreSQL 事务中保存，闭合“数据库成功但消息没发”的双写空窗。
 * 对应文档：07_rabbitmq/04_幂等与Outbox.md。
 */
@Service public class OutboxService{private final OutboxEventRepository repository;private final ObjectMapper json;private final Clock clock;public OutboxService(OutboxEventRepository r,ObjectMapper j,Clock c){repository=r;json=j;clock=c;}public UUID append(String aggregateType,String aggregateId,String eventType,Object payload){try{UUID id=UUID.randomUUID();EventEnvelope env=new EventEnvelope(id,eventType,1,clock.instant(),"mini-commerce",aggregateType,aggregateId,MDC.get("traceId"),json.valueToTree(payload));repository.save(new OutboxEventEntity(id,aggregateType,aggregateId,eventType,json.writeValueAsString(env),clock.instant()));return id;}catch(Exception e){throw new IllegalStateException("Outbox 序列化失败",e);}}}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/messaging/infrastructure/OutboxJdbcRepository.java": r'''package com.example.minicommerce.messaging.infrastructure;
import java.time.*;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Repository;import org.springframework.transaction.annotation.Transactional;
/** 多 Publisher 使用 FOR UPDATE SKIP LOCKED 领取不同批次，并使用租约恢复崩溃中的 PUBLISHING 记录。 */
@Repository public class OutboxJdbcRepository{private final JdbcTemplate jdbc;public OutboxJdbcRepository(JdbcTemplate j){jdbc=j;}
 @Transactional public List<ClaimedEvent> claim(String worker,int limit,Duration lease){String sql="""
 with picked as (
   select event_id from outbox_events
   where ((status in ('PENDING','FAILED') and next_attempt_at<=now()) or (status='PUBLISHING' and locked_until<now()))
   order by created_at for update skip locked limit ?
 )
 update outbox_events o set status='PUBLISHING',locked_by=?,locked_until=now()+(? * interval '1 millisecond'),attempt_count=attempt_count+1
 from picked where o.event_id=picked.event_id
 returning o.event_id,o.event_type,o.payload,o.attempt_count
 """;return jdbc.query(sql,(rs,n)->new ClaimedEvent(rs.getObject("event_id",UUID.class),rs.getString("event_type"),rs.getString("payload"),rs.getInt("attempt_count")),limit,worker,lease.toMillis());}
 @Transactional public void published(UUID id){jdbc.update("update outbox_events set status='PUBLISHED',published_at=now(),locked_by=null,locked_until=null,last_error=null where event_id=?",id);}
 @Transactional public void failed(UUID id,int attempt,String error){long delay=Math.min(300,1L<<Math.min(attempt,8));jdbc.update("update outbox_events set status='FAILED',next_attempt_at=now()+(? * interval '1 second'),locked_by=null,locked_until=null,last_error=? where event_id=?",delay,error.substring(0,Math.min(900,error.length())),id);}
 public record ClaimedEvent(UUID eventId,String eventType,String payload,int attemptCount){}
}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/messaging/config/RabbitTopology.java": r'''package com.example.minicommerce.messaging.config;
import org.springframework.amqp.core.*;import org.springframework.amqp.rabbit.core.RabbitTemplate;import org.springframework.context.annotation.*;
/** 对应文档：07_rabbitmq/02_Exchange_Queue_Routing.md、07_rabbitmq/03_Confirm_Ack_Retry_DLQ.md。 */
@Configuration public class RabbitTopology{
 public static final String EVENTS="commerce.events";public static final String DLX="commerce.dlx";public static final String NOTIFICATION_Q="notification.order-paid.v1";public static final String POINTS_Q="points.order-paid.v1";public static final String CACHE_Q="cache.product-changed.v1";
 @Bean TopicExchange commerceExchange(){return new TopicExchange(EVENTS,true,false);}@Bean DirectExchange deadLetterExchange(){return new DirectExchange(DLX,true,false);}
 private Queue durable(String name){return QueueBuilder.durable(name).deadLetterExchange(DLX).deadLetterRoutingKey(name+".dead").build();}
 @Bean Queue notificationQueue(){return durable(NOTIFICATION_Q);}@Bean Queue pointsQueue(){return durable(POINTS_Q);}@Bean Queue cacheQueue(){return durable(CACHE_Q);}
 @Bean Queue notificationDlq(){return QueueBuilder.durable(NOTIFICATION_Q+".dlq").build();}@Bean Queue pointsDlq(){return QueueBuilder.durable(POINTS_Q+".dlq").build();}@Bean Queue cacheDlq(){return QueueBuilder.durable(CACHE_Q+".dlq").build();}
 @Bean Binding notificationBinding(Queue notificationQueue,TopicExchange commerceExchange){return BindingBuilder.bind(notificationQueue).to(commerceExchange).with("order.paid.v1");}
 @Bean Binding pointsBinding(Queue pointsQueue,TopicExchange commerceExchange){return BindingBuilder.bind(pointsQueue).to(commerceExchange).with("order.paid.v1");}
 @Bean Binding cacheBinding(Queue cacheQueue,TopicExchange commerceExchange){return BindingBuilder.bind(cacheQueue).to(commerceExchange).with("product.changed.v1");}
 @Bean Binding notificationDead(Queue notificationDlq,DirectExchange deadLetterExchange){return BindingBuilder.bind(notificationDlq).to(deadLetterExchange).with(NOTIFICATION_Q+".dead");}
 @Bean Binding pointsDead(Queue pointsDlq,DirectExchange deadLetterExchange){return BindingBuilder.bind(pointsDlq).to(deadLetterExchange).with(POINTS_Q+".dead");}
 @Bean Binding cacheDead(Queue cacheDlq,DirectExchange deadLetterExchange){return BindingBuilder.bind(cacheDlq).to(deadLetterExchange).with(CACHE_Q+".dead");}
 @Bean RabbitTemplateCustomizer mandatoryReturns(){return template->template.setMandatory(true);}public interface RabbitTemplateCustomizer{void customize(RabbitTemplate template);}
 @Bean org.springframework.boot.ApplicationRunner customizeRabbit(RabbitTemplate template,RabbitTemplateCustomizer customizer){return args->customizer.customize(template);}
}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/messaging/application/OutboxPublisher.java": r'''package com.example.minicommerce.messaging.application;
import com.example.minicommerce.messaging.config.RabbitTopology;import com.example.minicommerce.messaging.infrastructure.OutboxJdbcRepository;import com.example.minicommerce.shared.config.AppProperties;import io.micrometer.core.instrument.MeterRegistry;import java.nio.charset.StandardCharsets;import java.util.UUID;import java.util.concurrent.TimeUnit;import org.slf4j.*;import org.springframework.amqp.core.*;import org.springframework.amqp.rabbit.connection.CorrelationData;import org.springframework.amqp.rabbit.core.RabbitTemplate;import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Component;
/** Outbox + Publisher Confirm 提供至少一次发布；标记 Published 前崩溃会重发，因此 Consumer 仍必须幂等。 */
@Component @ConditionalOnProperty(name="app.outbox.publisher-enabled",havingValue="true",matchIfMissing=true)
public class OutboxPublisher{private static final Logger log=LoggerFactory.getLogger(OutboxPublisher.class);private final OutboxJdbcRepository repository;private final RabbitTemplate rabbit;private final AppProperties properties;private final MeterRegistry metrics;private final String worker=UUID.randomUUID().toString();public OutboxPublisher(OutboxJdbcRepository r,RabbitTemplate rabbit,AppProperties p,MeterRegistry m){repository=r;this.rabbit=rabbit;properties=p;metrics=m;}
 @Scheduled(fixedDelayString="${app.outbox.poll-delay:500ms}") public void poll(){repository.claim(worker,properties.outbox().batchSize(),properties.outbox().lease()).forEach(this::publish);}
 private void publish(OutboxJdbcRepository.ClaimedEvent e){try{MessageProperties mp=new MessageProperties();mp.setContentType(MessageProperties.CONTENT_TYPE_JSON);mp.setMessageId(e.eventId().toString());mp.setHeader("eventType",e.eventType());Message message=new Message(e.payload().getBytes(StandardCharsets.UTF_8),mp);CorrelationData correlation=new CorrelationData(e.eventId().toString());rabbit.send(RabbitTopology.EVENTS,e.eventType(),message,correlation);CorrelationData.Confirm confirm=correlation.getFuture().get(properties.outbox().publishTimeout().toMillis(),TimeUnit.MILLISECONDS);if(!confirm.isAck())throw new IllegalStateException("broker nack: "+confirm.getReason());repository.published(e.eventId());metrics.counter("commerce.outbox.published").increment();}catch(Exception ex){log.warn("event=outbox_publish_failed eventId={} attempt={} reason={}",e.eventId(),e.attemptCount(),ex.toString());repository.failed(e.eventId(),e.attemptCount(),ex.toString());metrics.counter("commerce.outbox.failed").increment();}}
}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/messaging/application/ProcessedMessageService.java": r'''package com.example.minicommerce.messaging.application;
import java.util.UUID;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;
/** INSERT ... ON CONFLICT DO NOTHING 与业务副作用处于同一事务；业务失败时去重记录也回滚。 */
@Service public class ProcessedMessageService{private final JdbcTemplate jdbc;public ProcessedMessageService(JdbcTemplate j){jdbc=j;}public boolean claim(String consumer,UUID eventId){return jdbc.update("insert into processed_messages(consumer_name,event_id,processed_at) values (?,?,now()) on conflict do nothing",consumer,eventId)==1;}}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/notification/infrastructure/NotificationEntity.java": r'''package com.example.minicommerce.notification.infrastructure;
import jakarta.persistence.*;import java.time.Instant;import java.util.UUID;
@Entity @Table(name="notifications")public class NotificationEntity{@Id private UUID id;@Column(name="user_id",nullable=false)private Long userId;@Column(nullable=false,length=100)private String type;@Column(nullable=false,length=500)private String message;@Column(nullable=false)private boolean unread;@Column(name="created_at",nullable=false)private Instant createdAt;protected NotificationEntity(){}public NotificationEntity(Long u,String t,String m,Instant n){id=UUID.randomUUID();userId=u;type=t;message=m;unread=true;createdAt=n;}public UUID getId(){return id;}public Long getUserId(){return userId;}public String getMessage(){return message;}public boolean isUnread(){return unread;}public Instant getCreatedAt(){return createdAt;}}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/notification/infrastructure/NotificationRepository.java": r'''package com.example.minicommerce.notification.infrastructure;import java.util.*;import org.springframework.data.jpa.repository.JpaRepository;public interface NotificationRepository extends JpaRepository<NotificationEntity,UUID>{List<NotificationEntity> findTop50ByUserIdOrderByCreatedAtDesc(Long userId);}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/notification/infrastructure/PointsLedgerEntity.java": r'''package com.example.minicommerce.notification.infrastructure;
import jakarta.persistence.*;import java.time.Instant;import java.util.UUID;
@Entity @Table(name="points_ledger",uniqueConstraints=@UniqueConstraint(name="ux_points_order_reason",columnNames={"order_id","reason"}))public class PointsLedgerEntity{@Id@GeneratedValue(strategy=GenerationType.IDENTITY)private Long id;@Column(name="user_id",nullable=false)private Long userId;@Column(name="order_id",nullable=false)private UUID orderId;@Column(nullable=false,length=50)private String reason;@Column(nullable=false)private int points;@Column(name="created_at",nullable=false)private Instant createdAt;protected PointsLedgerEntity(){}public PointsLedgerEntity(Long u,UUID o,int p,Instant n){userId=u;orderId=o;reason="ORDER_PAID";points=p;createdAt=n;}}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/notification/infrastructure/PointsLedgerRepository.java": r'''package com.example.minicommerce.notification.infrastructure;import org.springframework.data.jpa.repository.JpaRepository;public interface PointsLedgerRepository extends JpaRepository<PointsLedgerEntity,Long>{}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/notification/application/OrderPaidConsumers.java": r'''package com.example.minicommerce.notification.application;
import com.example.minicommerce.messaging.application.*;import com.example.minicommerce.messaging.config.RabbitTopology;import com.example.minicommerce.notification.infrastructure.*;import com.fasterxml.jackson.databind.ObjectMapper;import java.math.BigDecimal;import java.time.Clock;import java.util.UUID;import org.springframework.amqp.rabbit.annotation.RabbitListener;import org.springframework.stereotype.Component;import org.springframework.transaction.annotation.Transactional;
/** 两个独立 Queue 表示通知和积分都要收到事件；同 Queue 多 Consumer 才是水平竞争消费。 */
@Component public class OrderPaidConsumers{private final ObjectMapper json;private final ProcessedMessageService processed;private final NotificationRepository notifications;private final PointsLedgerRepository points;private final Clock clock;public OrderPaidConsumers(ObjectMapper j,ProcessedMessageService p,NotificationRepository n,PointsLedgerRepository l,Clock c){json=j;processed=p;notifications=n;points=l;clock=c;}
 @RabbitListener(queues=RabbitTopology.NOTIFICATION_Q)@Transactional public void notifyUser(String raw)throws Exception{EventEnvelope e=json.readValue(raw,EventEnvelope.class);if(!processed.claim("notification-order-paid",e.eventId()))return;Long user=e.payload().get("userId").asLong();notifications.save(new NotificationEntity(user,"ORDER_PAID","订单 "+e.aggregateId()+" 已支付",clock.instant()));}
 @RabbitListener(queues=RabbitTopology.POINTS_Q)@Transactional public void addPoints(String raw)throws Exception{EventEnvelope e=json.readValue(raw,EventEnvelope.class);if(!processed.claim("points-order-paid",e.eventId()))return;Long user=e.payload().get("userId").asLong();BigDecimal total=e.payload().get("total").decimalValue();points.save(new PointsLedgerEntity(user,UUID.fromString(e.aggregateId()),total.divideToIntegralValue(BigDecimal.valueOf(100)).intValue(),clock.instant()));}
}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/catalog/application/ProductCacheInvalidationConsumer.java": r'''package com.example.minicommerce.catalog.application;
import com.example.minicommerce.messaging.application.*;import com.example.minicommerce.messaging.config.RabbitTopology;import com.fasterxml.jackson.databind.ObjectMapper;import org.springframework.amqp.rabbit.annotation.RabbitListener;import org.springframework.stereotype.Component;import org.springframework.transaction.annotation.Transactional;
@Component public class ProductCacheInvalidationConsumer{private final ObjectMapper json;private final ProcessedMessageService processed;private final ProductCacheService cache;public ProductCacheInvalidationConsumer(ObjectMapper j,ProcessedMessageService p,ProductCacheService c){json=j;processed=p;cache=c;}@RabbitListener(queues=RabbitTopology.CACHE_Q)@Transactional public void invalidate(String raw)throws Exception{EventEnvelope e=json.readValue(raw,EventEnvelope.class);if(!processed.claim("cache-product-changed",e.eventId()))return;cache.evict(e.payload().get("productId").asLong());}}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/notification/api/NotificationController.java": r'''package com.example.minicommerce.notification.api;
import com.example.minicommerce.notification.infrastructure.*;import com.example.minicommerce.shared.security.CurrentUser;import java.util.*;import org.springframework.web.bind.annotation.*;
@RestController@RequestMapping("/api/notifications")public class NotificationController{private final NotificationRepository repo;private final CurrentUser current;public NotificationController(NotificationRepository r,CurrentUser c){repo=r;current=c;}@GetMapping public List<View>list(){return repo.findTop50ByUserIdOrderByCreatedAtDesc(current.require().id()).stream().map(n->new View(n.getId(),n.getMessage(),n.isUnread(),n.getCreatedAt())).toList();}public record View(UUID id,String message,boolean unread,java.time.Instant createdAt){}}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/payment/domain/PaymentStatus.java": r'''package com.example.minicommerce.payment.domain;public enum PaymentStatus{INITIATED,PROCESSING,SUCCEEDED,DECLINED,UNKNOWN}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/payment/infrastructure/PaymentAttemptEntity.java": r'''package com.example.minicommerce.payment.infrastructure;
import com.example.minicommerce.payment.domain.PaymentStatus;import jakarta.persistence.*;import java.math.BigDecimal;import java.time.Instant;import java.util.UUID;
@Entity@Table(name="payment_attempts",uniqueConstraints=@UniqueConstraint(name="ux_payment_user_key",columnNames={"user_id","idempotency_key"}))public class PaymentAttemptEntity{@Id private UUID id;@Column(name="order_id",nullable=false)private UUID orderId;@Column(name="user_id",nullable=false)private Long userId;@Column(name="idempotency_key",nullable=false,length=128)private String idempotencyKey;@Column(name="request_hash",nullable=false,length=64)private String requestHash;@Enumerated(EnumType.STRING)@Column(nullable=false,length=20)private PaymentStatus status;@Column(nullable=false,precision=19,scale=2)private BigDecimal amount;@Column(nullable=false,length=3)private String currency;@Column(name="provider_reference",length=100)private String providerReference;@Column(name="last_error",length=500)private String lastError;@Column(name="processing_started_at")private Instant processingStartedAt;@Column(name="created_at",nullable=false)private Instant createdAt;@Column(name="updated_at",nullable=false)private Instant updatedAt;@Version@Column(nullable=false)private long version;protected PaymentAttemptEntity(){}public PaymentAttemptEntity(UUID id,UUID order,Long user,String key,String hash,BigDecimal amount,String currency,Instant now){this.id=id;orderId=order;userId=user;idempotencyKey=key;requestHash=hash;status=PaymentStatus.INITIATED;this.amount=amount;this.currency=currency;createdAt=now;updatedAt=now;}public UUID getId(){return id;}public UUID getOrderId(){return orderId;}public Long getUserId(){return userId;}public String getRequestHash(){return requestHash;}public PaymentStatus getStatus(){return status;}public BigDecimal getAmount(){return amount;}public String getCurrency(){return currency;}public String getProviderReference(){return providerReference;}public String getLastError(){return lastError;}public void succeeded(String ref,Instant now){status=PaymentStatus.SUCCEEDED;providerReference=ref;updatedAt=now;}public void declined(String error,Instant now){status=PaymentStatus.DECLINED;lastError=error;updatedAt=now;}public void unknown(String error,Instant now){status=PaymentStatus.UNKNOWN;lastError=error;updatedAt=now;}}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/payment/infrastructure/PaymentAttemptRepository.java": r'''package com.example.minicommerce.payment.infrastructure;
import com.example.minicommerce.payment.domain.PaymentStatus;import java.time.Instant;import java.util.*;import org.springframework.data.jpa.repository.*;import org.springframework.data.repository.query.Param;import jakarta.persistence.LockModeType;
public interface PaymentAttemptRepository extends JpaRepository<PaymentAttemptEntity,UUID>{Optional<PaymentAttemptEntity>findByUserIdAndIdempotencyKey(Long userId,String key);@Lock(LockModeType.PESSIMISTIC_WRITE)@Query("select p from PaymentAttemptEntity p where p.id=:id")Optional<PaymentAttemptEntity>findForUpdate(@Param("id")UUID id);@Modifying@Query(value="update payment_attempts set status='PROCESSING',processing_started_at=now(),updated_at=now(),version=version+1 where id=:id and (status='INITIATED' or (status='PROCESSING' and processing_started_at<:stale))",nativeQuery=true)int claim(@Param("id")UUID id,@Param("stale")Instant stale);}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/payment/infrastructure/PaymentWebhookRepository.java": r'''package com.example.minicommerce.payment.infrastructure;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Repository;@Repository public class PaymentWebhookRepository{private final JdbcTemplate jdbc;public PaymentWebhookRepository(JdbcTemplate j){jdbc=j;}public boolean claim(String eventId,String payload){return jdbc.update("insert into payment_webhook_events(provider_event_id,payload,received_at) values (?,?,now()) on conflict do nothing",eventId,payload)==1;}}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/payment/application/PaymentGateway.java": r'''package com.example.minicommerce.payment.application;
import java.math.BigDecimal;import java.util.UUID;
/** 外部支付是不可由数据库事务回滚的 Port，因此调用必须放在短数据库事务之外。 */
public interface PaymentGateway{GatewayResult charge(UUID paymentId,BigDecimal amount,String currency,String paymentToken);GatewayResult refund(UUID paymentId,BigDecimal amount);record GatewayResult(boolean success,boolean unknown,String reference,String error){public static GatewayResult success(String ref){return new GatewayResult(true,false,ref,null);}public static GatewayResult declined(String e){return new GatewayResult(false,false,null,e);}public static GatewayResult unknown(String e){return new GatewayResult(false,true,null,e);}}}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/payment/application/FakePaymentGateway.java": r'''package com.example.minicommerce.payment.application;
import java.math.BigDecimal;import java.util.UUID;import org.springframework.stereotype.Component;
/** 本地确定性支付模拟器：decline/timeout/unknown token 用于故障实验，不连接真实资金系统。 */
@Component public class FakePaymentGateway implements PaymentGateway{public GatewayResult charge(UUID id,BigDecimal amount,String currency,String token){if("decline".equalsIgnoreCase(token))return GatewayResult.declined("模拟拒付");if("unknown".equalsIgnoreCase(token)||"timeout".equalsIgnoreCase(token))return GatewayResult.unknown("模拟响应丢失，不能断言支付未发生");return GatewayResult.success("fake_"+id.toString().replace("-","").substring(0,18));}public GatewayResult refund(UUID id,BigDecimal amount){return GatewayResult.success("refund_"+id.toString().substring(0,8));}}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/payment/application/PaymentTransactionService.java": r'''package com.example.minicommerce.payment.application;
import com.example.minicommerce.audit.application.AuditService;import com.example.minicommerce.inventory.application.InventoryService;import com.example.minicommerce.messaging.application.OutboxService;import com.example.minicommerce.order.application.*;import com.example.minicommerce.order.infrastructure.*;import com.example.minicommerce.payment.domain.PaymentStatus;import com.example.minicommerce.payment.infrastructure.*;import com.example.minicommerce.promotion.application.CouponService;import com.example.minicommerce.shared.error.*;import com.example.minicommerce.shared.security.UserPrincipal;import java.nio.charset.StandardCharsets;import java.security.*;import java.time.Clock;import java.util.*;import java.util.stream.Collectors;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.*;
@Service public class PaymentTransactionService{private final PaymentAttemptRepository payments;private final OrderRepository orders;private final OrderItemRepository items;private final OrderQueryService query;private final InventoryService inventory;private final CouponService coupons;private final OutboxService outbox;private final AuditService audit;private final Clock clock;public PaymentTransactionService(PaymentAttemptRepository p,OrderRepository o,OrderItemRepository i,OrderQueryService q,InventoryService inv,CouponService c,OutboxService out,AuditService a,Clock clock){payments=p;orders=o;items=i;query=q;inventory=inv;coupons=c;outbox=out;audit=a;this.clock=clock;}
 @Transactional public PaymentView createOrGet(UUID orderId,UserPrincipal actor,String key,String paymentToken){if(key==null||key.isBlank())throw new BusinessException(ErrorCode.IDEMPOTENCY_KEY_REQUIRED,"支付必须提供 Idempotency-Key");OrderEntity order=orders.findForUpdate(orderId).orElseThrow(()->new BusinessException(ErrorCode.ORDER_NOT_FOUND,"订单不存在"));query.authorize(order,actor);if(order.getStatus()!=com.example.minicommerce.order.domain.OrderStatus.PENDING_PAYMENT)throw new BusinessException(ErrorCode.ORDER_NOT_PAYABLE,"订单不可支付");String hash=hash(orderId+":"+paymentToken);Optional<PaymentAttemptEntity>prior=payments.findByUserIdAndIdempotencyKey(actor.id(),key);if(prior.isPresent()){if(!prior.get().getRequestHash().equals(hash))throw new BusinessException(ErrorCode.IDEMPOTENCY_CONFLICT,"同一支付幂等键请求不同");return view(prior.get());}PaymentAttemptEntity p=payments.saveAndFlush(new PaymentAttemptEntity(UUID.randomUUID(),orderId,actor.id(),key,hash,order.getTotalAmount(),order.getCurrency(),clock.instant()));return view(p);}
 @Transactional public boolean claim(UUID paymentId){return payments.claim(paymentId,clock.instant().minusSeconds(120))==1;}
 @Transactional public PaymentView apply(UUID paymentId,PaymentGateway.GatewayResult result){PaymentAttemptEntity p=payments.findForUpdate(paymentId).orElseThrow();if(p.getStatus()==PaymentStatus.SUCCEEDED||p.getStatus()==PaymentStatus.DECLINED)return view(p);if(result.success()){OrderEntity order=orders.findForUpdate(p.getOrderId()).orElseThrow();if(order.getStatus()==com.example.minicommerce.order.domain.OrderStatus.PENDING_PAYMENT){order.markPaid(p.getId(),clock.instant());Map<Long,Integer>qty=items.findByOrderIdOrderById(order.getId()).stream().collect(Collectors.toMap(OrderItemEntity::getProductId,OrderItemEntity::getQuantity));inventory.confirmSale(qty);coupons.markUsed(order.getUserCouponId(),order.getId());outbox.append("ORDER",order.getId().toString(),"order.paid.v1",Map.of("orderId",order.getId(),"userId",order.getUserId(),"total",order.getTotalAmount(),"currency",order.getCurrency()));}p.succeeded(result.reference(),clock.instant());audit.record(p.getUserId(),"PAYMENT_SUCCEEDED","PAYMENT",p.getId(),null,Map.of("orderId",p.getOrderId(),"providerReference",result.reference()));}else if(result.unknown())p.unknown(result.error(),clock.instant());else p.declined(result.error(),clock.instant());return view(p);}
 public PaymentView get(UUID id,UserPrincipal actor){PaymentAttemptEntity p=payments.findById(id).orElseThrow();if(!p.getUserId().equals(actor.id())&&!actor.role().name().equals("ADMIN")&&!actor.role().name().equals("SUPPORT"))throw new BusinessException(ErrorCode.ACCESS_DENIED,"不能读取他人的支付");return view(p);}private String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}private static PaymentView view(PaymentAttemptEntity p){return new PaymentView(p.getId(),p.getOrderId(),p.getStatus().name(),p.getAmount(),p.getCurrency(),p.getProviderReference(),p.getLastError());}public record PaymentView(UUID paymentId,UUID orderId,String status,java.math.BigDecimal amount,String currency,String providerReference,String error){}
}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/payment/application/PaymentOrchestrator.java": r'''package com.example.minicommerce.payment.application;
import com.example.minicommerce.payment.application.PaymentTransactionService.PaymentView;import com.example.minicommerce.shared.security.UserPrincipal;import java.util.UUID;import org.springframework.stereotype.Service;
/** 三段式边界：短事务建意图 → 事务外调用外部支付 → 短事务落结果。避免长事务持锁等待网络。 */
@Service public class PaymentOrchestrator{private final PaymentTransactionService tx;private final PaymentGateway gateway;public PaymentOrchestrator(PaymentTransactionService tx,PaymentGateway gateway){this.tx=tx;this.gateway=gateway;}public PaymentView pay(UUID orderId,UserPrincipal actor,String key,String token){PaymentView p=tx.createOrGet(orderId,actor,key,token);if(!"INITIATED".equals(p.status())&&!"PROCESSING".equals(p.status()))return p;if(!tx.claim(p.paymentId()))return tx.get(p.paymentId(),actor);PaymentGateway.GatewayResult result=gateway.charge(p.paymentId(),p.amount(),p.currency(),token);return tx.apply(p.paymentId(),result);}}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/payment/application/WebhookSignature.java": r'''package com.example.minicommerce.payment.application;
import com.example.minicommerce.shared.config.AppProperties;import com.example.minicommerce.shared.error.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.util.HexFormat;import javax.crypto.Mac;import javax.crypto.spec.SecretKeySpec;import org.springframework.stereotype.Component;
@Component public class WebhookSignature{private final byte[] secret;public WebhookSignature(AppProperties p){secret=p.payment().webhookSecret().getBytes(StandardCharsets.UTF_8);}public void verify(String body,String signature){try{Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(secret,"HmacSHA256"));byte[] expected=mac.doFinal(body.getBytes(StandardCharsets.UTF_8));byte[] actual=HexFormat.of().parseHex(signature==null?"":signature);if(!MessageDigest.isEqual(expected,actual))throw new BusinessException(ErrorCode.PAYMENT_SIGNATURE_INVALID,"Webhook 签名无效");}catch(IllegalArgumentException e){throw new BusinessException(ErrorCode.PAYMENT_SIGNATURE_INVALID,"Webhook 签名格式无效");}catch(BusinessException e){throw e;}catch(Exception e){throw new IllegalStateException(e);}}}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/payment/application/PaymentWebhookService.java": r'''package com.example.minicommerce.payment.application;
import com.example.minicommerce.payment.infrastructure.PaymentWebhookRepository;import com.fasterxml.jackson.databind.ObjectMapper;import java.util.UUID;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
/** providerEventId 唯一约束使重复回调不会重复改变订单或库存。 */
@Service public class PaymentWebhookService{private final WebhookSignature signatures;private final PaymentWebhookRepository events;private final ObjectMapper json;private final PaymentTransactionService tx;public PaymentWebhookService(WebhookSignature s,PaymentWebhookRepository e,ObjectMapper j,PaymentTransactionService tx){signatures=s;events=e;json=j;this.tx=tx;}@Transactional public void handle(String body,String signature)throws Exception{signatures.verify(body,signature);WebhookPayload p=json.readValue(body,WebhookPayload.class);if(!events.claim(p.eventId(),body))return;if("payment.succeeded".equals(p.type()))tx.apply(p.paymentId(),PaymentGateway.GatewayResult.success(p.providerReference()));else if("payment.declined".equals(p.type()))tx.apply(p.paymentId(),PaymentGateway.GatewayResult.declined("provider webhook declined"));}public record WebhookPayload(String eventId,String type,UUID paymentId,String providerReference){}}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/payment/api/PaymentController.java": r'''package com.example.minicommerce.payment.api;
import com.example.minicommerce.payment.application.*;import com.example.minicommerce.payment.application.PaymentTransactionService.PaymentView;import com.example.minicommerce.shared.security.CurrentUser;import jakarta.validation.Valid;import jakarta.validation.constraints.NotBlank;import java.util.UUID;import org.springframework.web.bind.annotation.*;
@RestController@RequestMapping("/api/payments")public class PaymentController{private final PaymentOrchestrator payments;private final PaymentWebhookService webhooks;private final CurrentUser current;public PaymentController(PaymentOrchestrator p,PaymentWebhookService w,CurrentUser c){payments=p;webhooks=w;current=c;}@PostMapping("/orders/{orderId}")public PaymentView pay(@PathVariable UUID orderId,@RequestHeader("Idempotency-Key")String key,@Valid@RequestBody PayRequest request){return payments.pay(orderId,current.require(),key,request.paymentToken());}@PostMapping("/webhooks/fake")public void webhook(@RequestHeader(value="X-Payment-Signature",required=false)String signature,@RequestBody String body)throws Exception{webhooks.handle(body,signature);}public record PayRequest(@NotBlank String paymentToken){}}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/identity/application/DemoDataInitializer.java": r'''package com.example.minicommerce.identity.application;
import com.example.minicommerce.catalog.infrastructure.*;import com.example.minicommerce.identity.domain.UserRole;import com.example.minicommerce.identity.infrastructure.*;import com.example.minicommerce.inventory.infrastructure.*;import com.example.minicommerce.promotion.domain.CouponType;import com.example.minicommerce.promotion.infrastructure.*;import java.math.BigDecimal;import java.time.*;import org.springframework.boot.*;import org.springframework.context.annotation.Profile;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.stereotype.Component;import org.springframework.transaction.annotation.Transactional;
/** 本地演示数据只在 local Profile 创建，生产环境绝不创建默认账号。 */
@Component@Profile("local")public class DemoDataInitializer implements ApplicationRunner{private final UserRepository users;private final ProductRepository products;private final InventoryRepository inventory;private final CouponRepository coupons;private final UserCouponRepository userCoupons;private final PasswordEncoder passwords;public DemoDataInitializer(UserRepository u,ProductRepository p,InventoryRepository i,CouponRepository c,UserCouponRepository uc,PasswordEncoder pe){users=u;products=p;inventory=i;coupons=c;userCoupons=uc;passwords=pe;}@Override@Transactional public void run(ApplicationArguments args){UserEntity alice=users.findByEmailIgnoreCase("alice@example.com").orElseGet(()->users.save(new UserEntity("alice@example.com","Alice",passwords.encode("Password123!"),UserRole.USER)));users.findByEmailIgnoreCase("admin@example.com").orElseGet(()->users.save(new UserEntity("admin@example.com","Admin",passwords.encode("AdminPassword123!"),UserRole.ADMIN)));if(products.count()==0){ProductEntity keyboard=new ProductEntity("KB-001","机械键盘 A","用于演示历史成交快照",new BigDecimal("8000.00"),"JPY");keyboard.publish();products.save(keyboard);inventory.save(new InventoryEntity(keyboard.getId(),100));ProductEntity mouse=new ProductEntity("MS-001","无线鼠标","用于并发库存实验",new BigDecimal("3200.00"),"JPY");mouse.publish();products.save(mouse);inventory.save(new InventoryEntity(mouse.getId(),20));}CouponEntity coupon=coupons.findByCodeIgnoreCase("WELCOME10").orElseGet(()->coupons.save(new CouponEntity("WELCOME10",CouponType.PERCENT,new BigDecimal("10"),new BigDecimal("5000"),new BigDecimal("1000"),Instant.now().minus(1,ChronoUnit.DAYS),Instant.now().plus(365,ChronoUnit.DAYS))));userCoupons.findForUpdate(alice.getId(),coupon.getId()).orElseGet(()->userCoupons.save(new UserCouponEntity(alice.getId(),coupon.getId())));}}
'''.replace('import java.time.*;','import java.time.*;import java.time.temporal.ChronoUnit;'),
"mini-commerce/backend/src/main/java/com/example/minicommerce/observability/CommerceHealthIndicator.java": r'''package com.example.minicommerce.observability;
import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.boot.actuate.health.*;import org.springframework.stereotype.Component;
/** Readiness 检查权威 PostgreSQL；Redis 缓存故障不会让 Liveness 失败并触发所有实例重启。 */
@Component("commerceDatabase")public class CommerceHealthIndicator implements HealthIndicator{private final JdbcTemplate jdbc;public CommerceHealthIndicator(JdbcTemplate j){jdbc=j;}public Health health(){try{Integer one=jdbc.queryForObject("select 1",Integer.class);return Health.up().withDetail("database",one).build();}catch(Exception e){return Health.down(e).build();}}}
''',
"mini-commerce/backend/src/main/resources/db/migration/V001__baseline.sql": r'''create table app_users(
 id bigint generated always as identity primary key,email varchar(320) not null,display_name varchar(100) not null,
 password_hash varchar(100) not null,role varchar(20) not null check(role in('USER','ADMIN','SUPPORT')),enabled boolean not null default true,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index ux_users_email on app_users(lower(email));

create table refresh_tokens(id uuid primary key,user_id bigint not null references app_users(id),token_hash varchar(64) not null unique,
 expires_at timestamptz not null,revoked_at timestamptz,created_at timestamptz not null);

create table products(id bigint generated always as identity primary key,sku varchar(64) not null unique,name varchar(200) not null,
 description varchar(2000) not null,price numeric(19,2) not null check(price>0),currency char(3) not null,
 status varchar(20) not null check(status in('DRAFT','PUBLISHED','ARCHIVED')),version bigint not null default 0,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index ix_products_status_created on products(status,created_at desc);

create table inventory(product_id bigint primary key references products(id) on delete restrict,available integer not null check(available>=0),
 reserved integer not null default 0 check(reserved>=0),version bigint not null default 0,updated_at timestamptz not null default now());

create table carts(id bigint generated always as identity primary key,user_id bigint not null unique references app_users(id),
 created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table cart_items(id bigint generated always as identity primary key,cart_id bigint not null references carts(id) on delete cascade,
 product_id bigint not null references products(id),quantity integer not null check(quantity>0),created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),constraint ux_cart_product unique(cart_id,product_id));

create table coupons(id bigint generated always as identity primary key,code varchar(50) not null unique,type varchar(20) not null check(type in('PERCENT','FIXED')),
 value numeric(19,2) not null check(value>0),min_amount numeric(19,2) not null check(min_amount>=0),max_discount numeric(19,2),
 valid_from timestamptz not null,valid_until timestamptz not null,active boolean not null default true);
create table user_coupons(id bigint generated always as identity primary key,user_id bigint not null references app_users(id),coupon_id bigint not null references coupons(id),
 status varchar(20) not null check(status in('ISSUED','RESERVED','USED','EXPIRED')),reserved_order_id uuid,version bigint not null default 0,
 constraint ux_user_coupon unique(user_id,coupon_id));

create table orders(id uuid primary key,order_number varchar(40) not null unique,user_id bigint not null references app_users(id),
 status varchar(30) not null check(status in('PENDING_PAYMENT','PAID','FULFILLING','COMPLETED','CANCELLED','REFUNDING','REFUNDED')),
 subtotal numeric(19,2) not null check(subtotal>=0),discount numeric(19,2) not null check(discount>=0),total_amount numeric(19,2) not null check(total_amount>=0),
 currency char(3) not null,user_coupon_id bigint references user_coupons(id),payment_id uuid,created_at timestamptz not null,updated_at timestamptz not null,
 cancelled_at timestamptz,version bigint not null default 0);
create index ix_orders_user_created on orders(user_id,created_at desc,id desc);create index ix_orders_status_created on orders(status,created_at desc);
create table order_items(id uuid primary key,order_id uuid not null references orders(id) on delete restrict,product_id bigint not null references products(id),
 product_name_snapshot varchar(200) not null,sku_snapshot varchar(64) not null,unit_price_snapshot numeric(19,2) not null check(unit_price_snapshot>0),
 quantity integer not null check(quantity>0),line_total numeric(19,2) not null check(line_total>0),constraint ux_order_product unique(order_id,product_id));
create index ix_order_items_order on order_items(order_id);

create table idempotency_records(id uuid primary key,user_id bigint not null references app_users(id),idempotency_key varchar(128) not null,
 request_hash varchar(64) not null,status varchar(20) not null check(status in('PROCESSING','COMPLETED')),resource_id uuid,
 created_at timestamptz not null,expires_at timestamptz not null,constraint ux_idempotency_user_key unique(user_id,idempotency_key));

create table payment_attempts(id uuid primary key,order_id uuid not null references orders(id),user_id bigint not null references app_users(id),
 idempotency_key varchar(128) not null,request_hash varchar(64) not null,status varchar(20) not null check(status in('INITIATED','PROCESSING','SUCCEEDED','DECLINED','UNKNOWN')),
 amount numeric(19,2) not null,currency char(3) not null,provider_reference varchar(100),last_error varchar(500),processing_started_at timestamptz,
 created_at timestamptz not null,updated_at timestamptz not null,version bigint not null default 0,constraint ux_payment_user_key unique(user_id,idempotency_key));
create unique index ux_payment_success_per_order on payment_attempts(order_id) where status='SUCCEEDED';
create table payment_webhook_events(provider_event_id varchar(150) primary key,payload text not null,received_at timestamptz not null);

create table outbox_events(event_id uuid primary key,aggregate_type varchar(80) not null,aggregate_id varchar(100) not null,event_type varchar(100) not null,
 schema_version integer not null check(schema_version>0),payload text not null,status varchar(20) not null check(status in('PENDING','PUBLISHING','PUBLISHED','FAILED')),
 attempt_count integer not null default 0,next_attempt_at timestamptz not null,locked_by varchar(100),locked_until timestamptz,last_error varchar(1000),
 created_at timestamptz not null,published_at timestamptz);
create index ix_outbox_pending on outbox_events(next_attempt_at,created_at) where status in('PENDING','FAILED','PUBLISHING');
create table processed_messages(consumer_name varchar(100) not null,event_id uuid not null,processed_at timestamptz not null,primary key(consumer_name,event_id));

create table notifications(id uuid primary key,user_id bigint not null references app_users(id),type varchar(100) not null,message varchar(500) not null,
 unread boolean not null,created_at timestamptz not null);create index ix_notifications_user_created on notifications(user_id,created_at desc);
create table points_ledger(id bigint generated always as identity primary key,user_id bigint not null references app_users(id),order_id uuid not null references orders(id),
 reason varchar(50) not null,points integer not null,created_at timestamptz not null,constraint ux_points_order_reason unique(order_id,reason));
create table audit_log(id bigint generated always as identity primary key,actor_id bigint,action varchar(100) not null,resource_type varchar(100) not null,
 resource_id varchar(100) not null,result varchar(20) not null,trace_id varchar(128),before_json text,after_json text,created_at timestamptz not null);
create index ix_audit_resource on audit_log(resource_type,resource_id,created_at desc);
''',
"mini-commerce/backend/src/main/resources/db/migration/V002__operational_indexes.sql": r'''-- 对应文档：04_database_postgresql/03_索引与EXPLAIN.md。
-- 索引必须服务真实查询形状；不是“每列都建索引”。
create index if not exists ix_idempotency_expiry on idempotency_records(expires_at);
create index if not exists ix_refresh_expiry on refresh_tokens(expires_at) where revoked_at is null;
create index if not exists ix_payment_order_created on payment_attempts(order_id,created_at desc);
''',
"mini-commerce/backend/src/test/java/com/example/minicommerce/shared/domain/MoneyTest.java": r'''package com.example.minicommerce.shared.domain;import static org.assertj.core.api.Assertions.*;import java.math.BigDecimal;import org.junit.jupiter.api.Test;class MoneyTest{@Test void add_requiresSameCurrency(){assertThatThrownBy(()->new Money(new BigDecimal("1"),"JPY").add(new Money(new BigDecimal("1"),"USD"))).isInstanceOf(IllegalArgumentException.class);}@Test void multiply_usesDecimalMoney(){assertThat(new Money(new BigDecimal("8.00"),"JPY").multiply(3).amount()).isEqualByComparingTo("24.00");}}
''',
"mini-commerce/backend/src/test/java/com/example/minicommerce/order/domain/OrderEntityTest.java": r'''package com.example.minicommerce.order.domain;import static org.assertj.core.api.Assertions.*;import com.example.minicommerce.order.infrastructure.OrderEntity;import com.example.minicommerce.shared.error.BusinessException;import java.math.BigDecimal;import java.time.Instant;import java.util.UUID;import org.junit.jupiter.api.Test;class OrderEntityTest{@Test void cancelledOrder_cannotBePaid(){OrderEntity o=new OrderEntity(UUID.randomUUID(),"MC-X",1L,new BigDecimal("100"),BigDecimal.ZERO,new BigDecimal("100"),"JPY",null,Instant.parse("2026-01-01T00:00:00Z"));o.cancel(Instant.parse("2026-01-01T00:00:01Z"));assertThatThrownBy(()->o.markPaid(UUID.randomUUID(),Instant.now())).isInstanceOf(BusinessException.class);}@Test void duplicateCancel_isIdempotent(){OrderEntity o=new OrderEntity(UUID.randomUUID(),"MC-Y",1L,new BigDecimal("100"),BigDecimal.ZERO,new BigDecimal("100"),"JPY",null,Instant.now());o.cancel(Instant.now());o.cancel(Instant.now());assertThat(o.getStatus()).isEqualTo(OrderStatus.CANCELLED);}}
''',
"mini-commerce/backend/src/test/java/com/example/minicommerce/ArchitectureTest.java": r'''package com.example.minicommerce;import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.*;import com.tngtech.archunit.core.importer.ImportOption;import com.tngtech.archunit.junit.*;@AnalyzeClasses(packages="com.example.minicommerce",importOptions=ImportOption.DoNotIncludeTests.class)class ArchitectureTest{@ArchTest static final com.tngtech.archunit.lang.ArchRule controllers_do_not_reach_repositories=noClasses().that().resideInAPackage("..api..").should().dependOnClassesThat().resideInAPackage("..infrastructure..");@ArchTest static final com.tngtech.archunit.lang.ArchRule domain_is_framework_free=noClasses().that().resideInAPackage("..domain..").should().dependOnClassesThat().resideInAnyPackage("org.springframework..","jakarta.persistence..");}
''',
"mini-commerce/backend/src/test/java/com/example/minicommerce/support/AbstractPostgresIT.java": r'''package com.example.minicommerce.support;import org.junit.jupiter.api.BeforeAll;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.test.context.ActiveProfiles;import org.springframework.test.context.DynamicPropertyRegistry;import org.springframework.test.context.DynamicPropertySource;import org.testcontainers.containers.PostgreSQLContainer;import org.testcontainers.junit.jupiter.Container;import org.testcontainers.junit.jupiter.Testcontainers;@Testcontainers(disabledWithoutDocker=true)@SpringBootTest@ActiveProfiles("test")public abstract class AbstractPostgresIT{@Container static final PostgreSQLContainer<?> POSTGRES=new PostgreSQLContainer<>("postgres:17-alpine").withDatabaseName("commerce").withUsername("commerce").withPassword("commerce");@DynamicPropertySource static void props(DynamicPropertyRegistry r){r.add("spring.datasource.url",POSTGRES::getJdbcUrl);r.add("spring.datasource.username",POSTGRES::getUsername);r.add("spring.datasource.password",POSTGRES::getPassword);r.add("app.outbox.publisher-enabled",()->"false");}}
''',
"mini-commerce/backend/src/test/java/com/example/minicommerce/inventory/InventoryConcurrencyIT.java": r'''package com.example.minicommerce.inventory;import static org.assertj.core.api.Assertions.*;import com.example.minicommerce.catalog.infrastructure.*;import com.example.minicommerce.inventory.infrastructure.*;import com.example.minicommerce.support.AbstractPostgresIT;import java.math.BigDecimal;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.AtomicInteger;import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.transaction.support.TransactionTemplate;class InventoryConcurrencyIT extends AbstractPostgresIT{@Autowired ProductRepository products;@Autowired InventoryRepository inventory;@Autowired TransactionTemplate transactions;@Test void stockOne_twentyConcurrentReservations_onlyOneSucceeds()throws Exception{ProductEntity p=new ProductEntity("CONC-"+UUID.randomUUID(),"并发商品","test",new BigDecimal("1.00"),"JPY");p.publish();p=products.saveAndFlush(p);inventory.saveAndFlush(new InventoryEntity(p.getId(),1));int workers=20;ExecutorService pool=Executors.newFixedThreadPool(workers);CountDownLatch ready=new CountDownLatch(workers),start=new CountDownLatch(1);AtomicInteger success=new AtomicInteger();List<Future<?>>futures=new ArrayList<>();Long id=p.getId();for(int n=0;n<workers;n++)futures.add(pool.submit(()->{ready.countDown();start.await();transactions.executeWithoutResult(s->{if(inventory.reserve(id,1)==1)success.incrementAndGet();});return null;}));ready.await(5,TimeUnit.SECONDS);start.countDown();for(Future<?>f:futures)f.get(10,TimeUnit.SECONDS);pool.shutdownNow();InventoryEntity finalState=inventory.findById(id).orElseThrow();assertThat(success.get()).isEqualTo(1);assertThat(finalState.getAvailable()).isZero();assertThat(finalState.getReserved()).isEqualTo(1);}}
''',
"mini-commerce/backend/src/test/java/com/example/minicommerce/order/CreateOrderIT.java": r'''package com.example.minicommerce.order;import static org.assertj.core.api.Assertions.*;import com.example.minicommerce.catalog.infrastructure.*;import com.example.minicommerce.identity.domain.UserRole;import com.example.minicommerce.identity.infrastructure.*;import com.example.minicommerce.inventory.infrastructure.*;import com.example.minicommerce.messaging.infrastructure.OutboxEventRepository;import com.example.minicommerce.order.api.OrderDtos.*;import com.example.minicommerce.order.application.CreateOrderService;import com.example.minicommerce.order.infrastructure.*;import com.example.minicommerce.shared.error.BusinessException;import com.example.minicommerce.support.AbstractPostgresIT;import java.math.BigDecimal;import java.util.*;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;class CreateOrderIT extends AbstractPostgresIT{@Autowired UserRepository users;@Autowired ProductRepository products;@Autowired InventoryRepository inventory;@Autowired CreateOrderService service;@Autowired OrderRepository orders;@Autowired IdempotencyRecordRepository idempotency;@Autowired OutboxEventRepository outbox;Long userId;Long productId;@BeforeEach void data(){UserEntity u=users.save(new UserEntity(UUID.randomUUID()+"@example.com","buyer","hash",UserRole.USER));ProductEntity p=new ProductEntity("SKU-"+UUID.randomUUID(),"快照商品","test",new BigDecimal("8000.00"),"JPY");p.publish();p=products.saveAndFlush(p);inventory.saveAndFlush(new InventoryEntity(p.getId(),2));userId=u.getId();productId=p.getId();}@Test void create_writesOrderInventoryIdempotencyAndOutbox(){var result=service.create(userId,"key-"+UUID.randomUUID(),new CreateOrderRequest(List.of(new OrderLineRequest(productId,2)),null));assertThat(result.totalAmount()).isEqualByComparingTo("16000.00");assertThat(result.items().getFirst().productName()).isEqualTo("快照商品");assertThat(inventory.findById(productId).orElseThrow().getReserved()).isEqualTo(2);assertThat(idempotency.count()).isPositive();assertThat(outbox.count()).isPositive();}@Test void insufficientStock_rollsBackEveryWrite(){long beforeOrders=orders.count(),beforeIdem=idempotency.count(),beforeOutbox=outbox.count();assertThatThrownBy(()->service.create(userId,"key-"+UUID.randomUUID(),new CreateOrderRequest(List.of(new OrderLineRequest(productId,3)),null))).isInstanceOf(BusinessException.class);assertThat(orders.count()).isEqualTo(beforeOrders);assertThat(idempotency.count()).isEqualTo(beforeIdem);assertThat(outbox.count()).isEqualTo(beforeOutbox);assertThat(inventory.findById(productId).orElseThrow().getAvailable()).isEqualTo(2);}}
''',
"mini-commerce/backend/src/test/java/com/example/minicommerce/payment/WebhookSignatureTest.java": r'''package com.example.minicommerce.payment;import static org.assertj.core.api.Assertions.*;import com.example.minicommerce.payment.application.WebhookSignature;import com.example.minicommerce.shared.config.AppProperties;import com.example.minicommerce.shared.error.BusinessException;import java.time.Duration;import org.junit.jupiter.api.Test;class WebhookSignatureTest{@Test void invalidSignature_isRejected(){AppProperties p=new AppProperties(new AppProperties.Jwt("x","eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHg=",Duration.ofMinutes(1),Duration.ofDays(1)),new AppProperties.Payment("secret",Duration.ofMillis(1),Duration.ofMillis(1)),new AppProperties.Cache(Duration.ofMinutes(1),Duration.ofSeconds(1),Duration.ofSeconds(1)),new AppProperties.Outbox(1,Duration.ofSeconds(1),Duration.ofSeconds(1),Duration.ofSeconds(1)));WebhookSignature s=new WebhookSignature(p);assertThatThrownBy(()->s.verify("{}","00")).isInstanceOf(BusinessException.class);}}
''',
"mini-commerce/backend/src/test/resources/application.yml": r'''spring:
  task:
    scheduling:
      enabled: false
app:
  outbox:
    publisher-enabled: false
'''
}
