from __future__ import annotations

# 该文件覆盖前面脚手架中的教学简版，实现最终可提交版本的状态机、认证错误和支付幂等语义。
FILES: dict[str, str] = {
"mini-commerce/backend/src/main/java/com/example/minicommerce/shared/security/UserPrincipal.java": r'''package com.example.minicommerce.shared.security;
import com.example.minicommerce.identity.domain.UserRole;import com.example.minicommerce.identity.infrastructure.UserEntity;import java.util.*;import org.springframework.security.core.*;import org.springframework.security.core.authority.SimpleGrantedAuthority;import org.springframework.security.core.userdetails.UserDetails;
public record UserPrincipal(Long id,String email,String password,UserRole role,boolean enabled)implements UserDetails{public static UserPrincipal from(UserEntity u){return new UserPrincipal(u.getId(),u.getEmail(),u.getPasswordHash(),u.getRole(),u.isEnabled());}@Override public Collection<? extends GrantedAuthority>getAuthorities(){return List.of(new SimpleGrantedAuthority("ROLE_"+role.name()));}@Override public String getUsername(){return email;}@Override public String getPassword(){return password;}@Override public boolean isAccountNonExpired(){return true;}@Override public boolean isAccountNonLocked(){return true;}@Override public boolean isCredentialsNonExpired(){return true;}@Override public boolean isEnabled(){return enabled;}}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/shared/security/JwtAuthenticationFilter.java": r'''package com.example.minicommerce.shared.security;
import com.example.minicommerce.identity.infrastructure.UserRepository;import io.jsonwebtoken.JwtException;import jakarta.servlet.*;import jakarta.servlet.http.*;import java.io.IOException;import org.slf4j.*;import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;import org.springframework.security.core.context.SecurityContextHolder;import org.springframework.stereotype.Component;import org.springframework.web.filter.OncePerRequestFilter;
@Component public class JwtAuthenticationFilter extends OncePerRequestFilter{private static final Logger log=LoggerFactory.getLogger(JwtAuthenticationFilter.class);private final JwtService jwt;private final UserRepository users;public JwtAuthenticationFilter(JwtService j,UserRepository u){jwt=j;users=u;}@Override protected void doFilterInternal(HttpServletRequest request,HttpServletResponse response,FilterChain chain)throws ServletException,IOException{String header=request.getHeader("Authorization");if(header!=null&&header.startsWith("Bearer ")&&SecurityContextHolder.getContext().getAuthentication()==null){try{var claims=jwt.parse(header.substring(7));Number raw=claims.get("uid",Number.class);if(raw!=null)users.findById(raw.longValue()).filter(user->user.isEnabled()).ifPresent(user->{UserPrincipal principal=UserPrincipal.from(user);SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(principal,null,principal.getAuthorities()));MDC.put("userId",String.valueOf(principal.id()));});}catch(JwtException|IllegalArgumentException ex){log.debug("event=jwt_rejected reason={}",ex.getClass().getSimpleName());}}try{chain.doFilter(request,response);}finally{MDC.remove("userId");}}
}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/shared/security/ApiSecurityHandlers.java": r'''package com.example.minicommerce.shared.security;
import com.example.minicommerce.shared.error.ErrorCode;import com.fasterxml.jackson.databind.ObjectMapper;import jakarta.servlet.http.*;import java.io.IOException;import java.util.Map;import org.slf4j.MDC;import org.springframework.http.MediaType;import org.springframework.security.access.AccessDeniedException;import org.springframework.security.core.AuthenticationException;import org.springframework.security.web.*;import org.springframework.stereotype.Component;
@Component public class ApiSecurityHandlers implements AuthenticationEntryPoint,AccessDeniedHandler{private final ObjectMapper json;public ApiSecurityHandlers(ObjectMapper j){json=j;}@Override public void commence(HttpServletRequest req,HttpServletResponse res,AuthenticationException ex)throws IOException{write(res,401,ErrorCode.AUTHENTICATION_FAILED,"需要有效登录凭证");}@Override public void handle(HttpServletRequest req,HttpServletResponse res,AccessDeniedException ex)throws IOException{write(res,403,ErrorCode.ACCESS_DENIED,"没有执行该操作的权限");}private void write(HttpServletResponse res,int status,ErrorCode code,String message)throws IOException{res.setStatus(status);res.setContentType(MediaType.APPLICATION_JSON_VALUE);json.writeValue(res.getOutputStream(),Map.of("code",code.name(),"message",message,"traceId",String.valueOf(MDC.get("traceId"))));}}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/shared/security/SecurityConfiguration.java": r'''package com.example.minicommerce.shared.security;
import com.example.minicommerce.shared.web.RateLimitFilter;import org.springframework.context.annotation.*;import org.springframework.http.HttpMethod;import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity;import org.springframework.security.config.annotation.web.builders.HttpSecurity;import org.springframework.security.config.http.SessionCreationPolicy;import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.security.web.SecurityFilterChain;import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;
/** Bearer Token 模式不依赖浏览器自动 Cookie；改为 Session Cookie 时必须重新启用 CSRF Token。 */
@Configuration@EnableMethodSecurity public class SecurityConfiguration{@Bean SecurityFilterChain filterChain(HttpSecurity http,JwtAuthenticationFilter jwt,RateLimitFilter rateLimit,ApiSecurityHandlers handlers)throws Exception{return http.csrf(csrf->csrf.disable()).sessionManagement(s->s.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).exceptionHandling(e->e.authenticationEntryPoint(handlers).accessDeniedHandler(handlers)).authorizeHttpRequests(auth->auth.requestMatchers("/actuator/health/**","/actuator/info").permitAll().requestMatchers("/api/auth/**").permitAll().requestMatchers(HttpMethod.GET,"/api/products/**").permitAll().requestMatchers("/api/payments/webhooks/**").permitAll().anyRequest().authenticated()).addFilterBefore(jwt,UsernamePasswordAuthenticationFilter.class).addFilterAfter(rateLimit,JwtAuthenticationFilter.class).build();}@Bean PasswordEncoder passwordEncoder(){return new BCryptPasswordEncoder(12);}}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/audit/infrastructure/AuditLogEntity.java": r'''package com.example.minicommerce.audit.infrastructure;
import jakarta.persistence.*;import java.time.Instant;
@Entity@Table(name="audit_log",indexes=@Index(name="ix_audit_resource",columnList="resource_type,resource_id,created_at"))public class AuditLogEntity{@Id@GeneratedValue(strategy=GenerationType.IDENTITY)private Long id;@Column(name="actor_id")private Long actorId;@Column(nullable=false,length=100)private String action;@Column(name="resource_type",nullable=false,length=100)private String resourceType;@Column(name="resource_id",nullable=false,length=100)private String resourceId;@Column(nullable=false,length=20)private String result;@Column(name="trace_id",length=128)private String traceId;@Column(name="before_json",columnDefinition="text")private String beforeJson;@Column(name="after_json",columnDefinition="text")private String afterJson;@Column(name="created_at",nullable=false)private Instant createdAt;protected AuditLogEntity(){}public AuditLogEntity(Long actorId,String action,String resourceType,String resourceId,String result,String traceId,String beforeJson,String afterJson,Instant createdAt){this.actorId=actorId;this.action=action;this.resourceType=resourceType;this.resourceId=resourceId;this.result=result;this.traceId=traceId;this.beforeJson=beforeJson;this.afterJson=afterJson;this.createdAt=createdAt;}}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/order/infrastructure/OrderEntity.java": r'''package com.example.minicommerce.order.infrastructure;
import com.example.minicommerce.order.domain.OrderStatus;import com.example.minicommerce.shared.error.*;import jakarta.persistence.*;import java.math.BigDecimal;import java.time.Instant;import java.util.*;
/** 状态转换集中在领域方法，数据库 CHECK 保护合法值，二者共同而非互相替代。 */
@Entity@Table(name="orders",indexes={@Index(name="ix_orders_user_created",columnList="user_id,created_at"),@Index(name="ix_orders_status_created",columnList="status,created_at")})public class OrderEntity{@Id private UUID id;@Column(name="order_number",nullable=false,unique=true,length=40)private String orderNumber;@Column(name="user_id",nullable=false)private Long userId;@Enumerated(EnumType.STRING)@Column(nullable=false,length=30)private OrderStatus status;@Column(nullable=false,precision=19,scale=2)private BigDecimal subtotal;@Column(nullable=false,precision=19,scale=2)private BigDecimal discount;@Column(name="total_amount",nullable=false,precision=19,scale=2)private BigDecimal totalAmount;@Column(nullable=false,length=3)private String currency;@Column(name="user_coupon_id")private Long userCouponId;@Column(name="payment_id")private UUID paymentId;@Column(name="created_at",nullable=false)private Instant createdAt;@Column(name="updated_at",nullable=false)private Instant updatedAt;@Column(name="cancelled_at")private Instant cancelledAt;@Version@Column(nullable=false)private long version;protected OrderEntity(){}public OrderEntity(UUID id,String number,Long userId,BigDecimal subtotal,BigDecimal discount,BigDecimal total,String currency,Long userCouponId,Instant now){this.id=id;orderNumber=number;this.userId=userId;status=OrderStatus.PENDING_PAYMENT;this.subtotal=subtotal;this.discount=discount;totalAmount=total;this.currency=currency;this.userCouponId=userCouponId;createdAt=now;updatedAt=now;}public UUID getId(){return id;}public String getOrderNumber(){return orderNumber;}public Long getUserId(){return userId;}public OrderStatus getStatus(){return status;}public BigDecimal getSubtotal(){return subtotal;}public BigDecimal getDiscount(){return discount;}public BigDecimal getTotalAmount(){return totalAmount;}public String getCurrency(){return currency;}public Long getUserCouponId(){return userCouponId;}public UUID getPaymentId(){return paymentId;}public Instant getCreatedAt(){return createdAt;}public long getVersion(){return version;}
 public boolean cancel(Instant now){if(status==OrderStatus.CANCELLED)return false;if(status!=OrderStatus.PENDING_PAYMENT)throw new BusinessException(ErrorCode.ORDER_NOT_CANCELLABLE,"当前订单状态不允许取消",Map.of("status",status));status=OrderStatus.CANCELLED;cancelledAt=now;updatedAt=now;return true;}
 public boolean markPaid(UUID paymentId,Instant now){if(status==OrderStatus.PAID&&Objects.equals(this.paymentId,paymentId))return false;if(status!=OrderStatus.PENDING_PAYMENT)throw new BusinessException(ErrorCode.ORDER_NOT_PAYABLE,"当前订单状态不允许支付",Map.of("status",status));this.paymentId=paymentId;status=OrderStatus.PAID;updatedAt=now;return true;}
 public void requestRefund(Instant now){if(status==OrderStatus.REFUNDING)return;if(status!=OrderStatus.PAID&&status!=OrderStatus.FULFILLING)throw new BusinessException(ErrorCode.ORDER_NOT_REFUNDABLE,"当前订单状态不允许退款");status=OrderStatus.REFUNDING;updatedAt=now;}
 public void markRefunded(Instant now){if(status==OrderStatus.REFUNDED)return;if(status!=OrderStatus.REFUNDING)throw new BusinessException(ErrorCode.ORDER_NOT_REFUNDABLE,"订单未处于退款中");status=OrderStatus.REFUNDED;updatedAt=now;}
 public void refundFailed(Instant now){if(status==OrderStatus.REFUNDING){status=OrderStatus.PAID;updatedAt=now;}}
}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/order/application/OrderCommandService.java": r'''package com.example.minicommerce.order.application;
import static com.example.minicommerce.order.api.OrderDtos.*;import com.example.minicommerce.audit.application.AuditService;import com.example.minicommerce.inventory.application.InventoryService;import com.example.minicommerce.messaging.application.OutboxService;import com.example.minicommerce.order.infrastructure.*;import com.example.minicommerce.promotion.application.CouponService;import com.example.minicommerce.shared.error.*;import com.example.minicommerce.shared.security.UserPrincipal;import java.time.Clock;import java.util.*;import java.util.stream.Collectors;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class OrderCommandService{private final OrderRepository orders;private final OrderItemRepository items;private final InventoryService inventory;private final CouponService coupons;private final OutboxService outbox;private final OrderQueryService query;private final AuditService audit;private final Clock clock;public OrderCommandService(OrderRepository o,OrderItemRepository i,InventoryService inv,CouponService c,OutboxService out,OrderQueryService q,AuditService a,Clock clock){orders=o;items=i;inventory=inv;coupons=c;outbox=out;query=q;audit=a;this.clock=clock;}@Transactional public OrderResponse cancel(UUID id,UserPrincipal actor){OrderEntity order=orders.findForUpdate(id).orElseThrow(()->new BusinessException(ErrorCode.ORDER_NOT_FOUND,"订单不存在"));query.authorize(order,actor);List<OrderItemEntity>lines=items.findByOrderIdOrderById(id);String before=order.getStatus().name();if(!order.cancel(clock.instant()))return OrderMapper.view(order,lines);Map<Long,Integer>qty=lines.stream().collect(Collectors.toMap(OrderItemEntity::getProductId,OrderItemEntity::getQuantity));inventory.release(qty);coupons.release(order.getUserCouponId(),id);outbox.append("ORDER",id.toString(),"order.cancelled.v1",Map.of("orderId",id,"userId",order.getUserId()));audit.record(actor.id(),"ORDER_CANCEL","ORDER",id,Map.of("status",before),Map.of("status",order.getStatus()));return OrderMapper.view(order,lines);}}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/payment/application/PaymentTransactionService.java": r'''package com.example.minicommerce.payment.application;
import com.example.minicommerce.audit.application.AuditService;import com.example.minicommerce.inventory.application.InventoryService;import com.example.minicommerce.messaging.application.OutboxService;import com.example.minicommerce.order.application.*;import com.example.minicommerce.order.domain.OrderStatus;import com.example.minicommerce.order.infrastructure.*;import com.example.minicommerce.payment.domain.PaymentStatus;import com.example.minicommerce.payment.infrastructure.*;import com.example.minicommerce.promotion.application.CouponService;import com.example.minicommerce.shared.error.*;import com.example.minicommerce.shared.security.UserPrincipal;import java.nio.charset.StandardCharsets;import java.security.*;import java.time.Clock;import java.util.*;import java.util.stream.Collectors;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
/** 支付 API 幂等先于订单当前状态判断，因此客户端在成功响应丢失后重试，仍能得到第一次结果。 */
@Service public class PaymentTransactionService{private final PaymentAttemptRepository payments;private final OrderRepository orders;private final OrderItemRepository items;private final OrderQueryService query;private final InventoryService inventory;private final CouponService coupons;private final OutboxService outbox;private final AuditService audit;private final Clock clock;public PaymentTransactionService(PaymentAttemptRepository p,OrderRepository o,OrderItemRepository i,OrderQueryService q,InventoryService inv,CouponService c,OutboxService out,AuditService a,Clock clock){payments=p;orders=o;items=i;query=q;inventory=inv;coupons=c;outbox=out;audit=a;this.clock=clock;}
 @Transactional public PaymentView createOrGet(UUID orderId,UserPrincipal actor,String key,String paymentToken){if(key==null||key.isBlank())throw new BusinessException(ErrorCode.IDEMPOTENCY_KEY_REQUIRED,"支付必须提供 Idempotency-Key");String hash=hash(orderId+":"+paymentToken);Optional<PaymentAttemptEntity>prior=payments.findByUserIdAndIdempotencyKey(actor.id(),key);if(prior.isPresent()){PaymentAttemptEntity p=prior.get();if(!p.getRequestHash().equals(hash)||!p.getOrderId().equals(orderId))throw new BusinessException(ErrorCode.IDEMPOTENCY_CONFLICT,"同一支付幂等键请求不同");return view(p);}OrderEntity order=orders.findForUpdate(orderId).orElseThrow(()->new BusinessException(ErrorCode.ORDER_NOT_FOUND,"订单不存在"));query.authorize(order,actor);if(order.getStatus()!=OrderStatus.PENDING_PAYMENT)throw new BusinessException(ErrorCode.ORDER_NOT_PAYABLE,"订单不可支付");PaymentAttemptEntity p=payments.saveAndFlush(new PaymentAttemptEntity(UUID.randomUUID(),orderId,actor.id(),key,hash,order.getTotalAmount(),order.getCurrency(),clock.instant()));return view(p);}
 @Transactional public boolean claim(UUID paymentId){return payments.claim(paymentId,clock.instant().minusSeconds(120))==1;}
 @Transactional public PaymentView apply(UUID paymentId,PaymentGateway.GatewayResult result){PaymentAttemptEntity p=payments.findForUpdate(paymentId).orElseThrow();if(p.getStatus()==PaymentStatus.SUCCEEDED||p.getStatus()==PaymentStatus.DECLINED)return view(p);if(result.success()){OrderEntity order=orders.findForUpdate(p.getOrderId()).orElseThrow();if(order.markPaid(p.getId(),clock.instant())){Map<Long,Integer>qty=items.findByOrderIdOrderById(order.getId()).stream().collect(Collectors.toMap(OrderItemEntity::getProductId,OrderItemEntity::getQuantity));inventory.confirmSale(qty);coupons.markUsed(order.getUserCouponId(),order.getId());outbox.append("ORDER",order.getId().toString(),"order.paid.v1",Map.of("orderId",order.getId(),"userId",order.getUserId(),"total",order.getTotalAmount(),"currency",order.getCurrency()));}p.succeeded(result.reference(),clock.instant());audit.record(p.getUserId(),"PAYMENT_SUCCEEDED","PAYMENT",p.getId(),null,Map.of("orderId",p.getOrderId(),"providerReference",result.reference()));}else if(result.unknown())p.unknown(result.error(),clock.instant());else p.declined(result.error(),clock.instant());return view(p);}
 @Transactional(readOnly=true)public PaymentView get(UUID id,UserPrincipal actor){PaymentAttemptEntity p=payments.findById(id).orElseThrow();if(!p.getUserId().equals(actor.id())&&!actor.role().name().equals("ADMIN")&&!actor.role().name().equals("SUPPORT"))throw new BusinessException(ErrorCode.ACCESS_DENIED,"不能读取他人的支付");return view(p);}private String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}public static PaymentView view(PaymentAttemptEntity p){return new PaymentView(p.getId(),p.getOrderId(),p.getStatus().name(),p.getAmount(),p.getCurrency(),p.getProviderReference(),p.getLastError());}public record PaymentView(UUID paymentId,UUID orderId,String status,java.math.BigDecimal amount,String currency,String providerReference,String error){}
}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/messaging/application/OutboxPublisher.java": r'''package com.example.minicommerce.messaging.application;
import com.example.minicommerce.messaging.config.RabbitTopology;import com.example.minicommerce.messaging.infrastructure.OutboxJdbcRepository;import com.example.minicommerce.shared.config.AppProperties;import io.micrometer.core.instrument.MeterRegistry;import java.nio.charset.StandardCharsets;import java.util.UUID;import java.util.concurrent.TimeUnit;import org.slf4j.*;import org.springframework.amqp.core.*;import org.springframework.amqp.rabbit.connection.CorrelationData;import org.springframework.amqp.rabbit.core.RabbitTemplate;import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Component;
@Component@ConditionalOnProperty(name="app.outbox.publisher-enabled",havingValue="true",matchIfMissing=true)public class OutboxPublisher{private static final Logger log=LoggerFactory.getLogger(OutboxPublisher.class);private final OutboxJdbcRepository repository;private final RabbitTemplate rabbit;private final AppProperties properties;private final MeterRegistry metrics;private final String worker=UUID.randomUUID().toString();public OutboxPublisher(OutboxJdbcRepository r,RabbitTemplate rabbit,AppProperties p,MeterRegistry m){repository=r;this.rabbit=rabbit;properties=p;metrics=m;}@Scheduled(fixedDelayString="${app.outbox.poll-delay:500ms}")public void poll(){repository.claim(worker,properties.outbox().batchSize(),properties.outbox().lease()).forEach(this::publish);}private void publish(OutboxJdbcRepository.ClaimedEvent e){try{MessageProperties mp=new MessageProperties();mp.setContentType(MessageProperties.CONTENT_TYPE_TEXT_PLAIN);mp.setContentEncoding(StandardCharsets.UTF_8.name());mp.setMessageId(e.eventId().toString());mp.setHeader("eventType",e.eventType());Message message=new Message(e.payload().getBytes(StandardCharsets.UTF_8),mp);CorrelationData correlation=new CorrelationData(e.eventId().toString());rabbit.send(RabbitTopology.EVENTS,e.eventType(),message,correlation);CorrelationData.Confirm confirm=correlation.getFuture().get(properties.outbox().publishTimeout().toMillis(),TimeUnit.MILLISECONDS);if(!confirm.isAck())throw new IllegalStateException("broker nack: "+confirm.getReason());repository.published(e.eventId());metrics.counter("commerce.outbox.published").increment();}catch(Exception ex){log.warn("event=outbox_publish_failed eventId={} attempt={} reason={}",e.eventId(),e.attemptCount(),ex.toString());repository.failed(e.eventId(),e.attemptCount(),ex.toString());metrics.counter("commerce.outbox.failed").increment();}}}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/refund/infrastructure/RefundEntity.java": r'''package com.example.minicommerce.refund.infrastructure;
import jakarta.persistence.*;import java.math.BigDecimal;import java.time.Instant;import java.util.UUID;
@Entity@Table(name="refunds",uniqueConstraints=@UniqueConstraint(name="ux_refund_payment_key",columnNames={"payment_id","idempotency_key"}))public class RefundEntity{@Id private UUID id;@Column(name="payment_id",nullable=false)private UUID paymentId;@Column(name="order_id",nullable=false)private UUID orderId;@Column(name="user_id",nullable=false)private Long userId;@Column(name="idempotency_key",nullable=false,length=128)private String key;@Column(nullable=false,length=20)private String status;@Column(nullable=false,precision=19,scale=2)private BigDecimal amount;@Column(name="provider_reference",length=100)private String providerReference;@Column(name="last_error",length=500)private String lastError;@Column(name="created_at",nullable=false)private Instant createdAt;@Column(name="updated_at",nullable=false)private Instant updatedAt;protected RefundEntity(){}public RefundEntity(UUID paymentId,UUID orderId,Long userId,String key,BigDecimal amount,Instant now){id=UUID.randomUUID();this.paymentId=paymentId;this.orderId=orderId;this.userId=userId;this.key=key;this.amount=amount;status="INITIATED";createdAt=now;updatedAt=now;}public UUID getId(){return id;}public UUID getPaymentId(){return paymentId;}public UUID getOrderId(){return orderId;}public Long getUserId(){return userId;}public String getStatus(){return status;}public BigDecimal getAmount(){return amount;}public String getProviderReference(){return providerReference;}public String getLastError(){return lastError;}public void success(String ref,Instant now){status="SUCCEEDED";providerReference=ref;updatedAt=now;}public void unknown(String e,Instant now){status="UNKNOWN";lastError=e;updatedAt=now;}public void failed(String e,Instant now){status="FAILED";lastError=e;updatedAt=now;}}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/refund/infrastructure/RefundRepository.java": r'''package com.example.minicommerce.refund.infrastructure;import java.util.*;import org.springframework.data.jpa.repository.*;import org.springframework.data.repository.query.Param;import jakarta.persistence.LockModeType;public interface RefundRepository extends JpaRepository<RefundEntity,UUID>{Optional<RefundEntity>findByPaymentIdAndKey(UUID paymentId,String key);@Lock(LockModeType.PESSIMISTIC_WRITE)@Query("select r from RefundEntity r where r.id=:id")Optional<RefundEntity>findForUpdate(@Param("id")UUID id);}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/refund/application/RefundService.java": r'''package com.example.minicommerce.refund.application;
import com.example.minicommerce.messaging.application.OutboxService;import com.example.minicommerce.order.application.OrderQueryService;import com.example.minicommerce.order.infrastructure.*;import com.example.minicommerce.payment.application.*;import com.example.minicommerce.payment.infrastructure.*;import com.example.minicommerce.refund.infrastructure.*;import com.example.minicommerce.shared.error.*;import com.example.minicommerce.shared.security.UserPrincipal;import java.time.Clock;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class RefundService{private final RefundRepository refunds;private final PaymentAttemptRepository payments;private final OrderRepository orders;private final OrderQueryService query;private final PaymentGateway gateway;private final OutboxService outbox;private final Clock clock;public RefundService(RefundRepository r,PaymentAttemptRepository p,OrderRepository o,OrderQueryService q,PaymentGateway g,OutboxService out,Clock c){refunds=r;payments=p;orders=o;query=q;gateway=g;outbox=out;clock=c;}public RefundView refund(UUID paymentId,UserPrincipal actor,String key){RefundView begun=begin(paymentId,actor,key);if(!"INITIATED".equals(begun.status()))return begun;PaymentGateway.GatewayResult result=gateway.refund(paymentId,begun.amount());return finish(begun.refundId(),result);}@Transactional public RefundView begin(UUID paymentId,UserPrincipal actor,String key){if(key==null||key.isBlank())throw new BusinessException(ErrorCode.IDEMPOTENCY_KEY_REQUIRED,"退款必须提供 Idempotency-Key");Optional<RefundEntity>prior=refunds.findByPaymentIdAndKey(paymentId,key);if(prior.isPresent())return view(prior.get());PaymentAttemptEntity payment=payments.findForUpdate(paymentId).orElseThrow(()->new BusinessException(ErrorCode.ORDER_NOT_REFUNDABLE,"支付不存在"));if(!payment.getUserId().equals(actor.id())&&!actor.role().name().equals("ADMIN"))throw new BusinessException(ErrorCode.ACCESS_DENIED,"不能退款他人的订单");if(payment.getStatus()!=com.example.minicommerce.payment.domain.PaymentStatus.SUCCEEDED)throw new BusinessException(ErrorCode.ORDER_NOT_REFUNDABLE,"支付未成功");OrderEntity order=orders.findForUpdate(payment.getOrderId()).orElseThrow();query.authorize(order,actor);order.requestRefund(clock.instant());return view(refunds.save(new RefundEntity(paymentId,order.getId(),actor.id(),key,payment.getAmount(),clock.instant())));}@Transactional public RefundView finish(UUID id,PaymentGateway.GatewayResult result){RefundEntity refund=refunds.findForUpdate(id).orElseThrow();OrderEntity order=orders.findForUpdate(refund.getOrderId()).orElseThrow();if("SUCCEEDED".equals(refund.getStatus())||"FAILED".equals(refund.getStatus()))return view(refund);if(result.success()){refund.success(result.reference(),clock.instant());order.markRefunded(clock.instant());outbox.append("ORDER",order.getId().toString(),"order.refunded.v1",Map.of("orderId",order.getId(),"userId",order.getUserId(),"amount",refund.getAmount()));}else if(result.unknown())refund.unknown(result.error(),clock.instant());else{refund.failed(result.error(),clock.instant());order.refundFailed(clock.instant());}return view(refund);}private static RefundView view(RefundEntity r){return new RefundView(r.getId(),r.getPaymentId(),r.getOrderId(),r.getStatus(),r.getAmount(),r.getProviderReference(),r.getLastError());}public record RefundView(UUID refundId,UUID paymentId,UUID orderId,String status,java.math.BigDecimal amount,String providerReference,String error){}
}
''',
"mini-commerce/backend/src/main/java/com/example/minicommerce/payment/api/PaymentController.java": r'''package com.example.minicommerce.payment.api;
import com.example.minicommerce.payment.application.*;import com.example.minicommerce.payment.application.PaymentTransactionService.PaymentView;import com.example.minicommerce.refund.application.RefundService;import com.example.minicommerce.refund.application.RefundService.RefundView;import com.example.minicommerce.shared.security.CurrentUser;import jakarta.validation.Valid;import jakarta.validation.constraints.NotBlank;import java.util.UUID;import org.springframework.web.bind.annotation.*;
@RestController@RequestMapping("/api/payments")public class PaymentController{private final PaymentOrchestrator payments;private final PaymentWebhookService webhooks;private final RefundService refunds;private final CurrentUser current;public PaymentController(PaymentOrchestrator p,PaymentWebhookService w,RefundService r,CurrentUser c){payments=p;webhooks=w;refunds=r;current=c;}@PostMapping("/orders/{orderId}")public PaymentView pay(@PathVariable UUID orderId,@RequestHeader("Idempotency-Key")String key,@Valid@RequestBody PayRequest request){return payments.pay(orderId,current.require(),key,request.paymentToken());}@PostMapping("/{paymentId}/refunds")public RefundView refund(@PathVariable UUID paymentId,@RequestHeader("Idempotency-Key")String key){return refunds.refund(paymentId,current.require(),key);}@PostMapping("/webhooks/fake")public void webhook(@RequestHeader(value="X-Payment-Signature",required=false)String signature,@RequestBody String body)throws Exception{webhooks.handle(body,signature);}public record PayRequest(@NotBlank String paymentToken){}}
''',
"mini-commerce/backend/src/main/resources/db/migration/V003__refunds.sql": r'''create table refunds(
 id uuid primary key,payment_id uuid not null references payment_attempts(id),order_id uuid not null references orders(id),
 user_id bigint not null references app_users(id),idempotency_key varchar(128) not null,
 status varchar(20) not null check(status in('INITIATED','SUCCEEDED','FAILED','UNKNOWN')),
 amount numeric(19,2) not null check(amount>0),provider_reference varchar(100),last_error varchar(500),
 created_at timestamptz not null,updated_at timestamptz not null,
 constraint ux_refund_payment_key unique(payment_id,idempotency_key));
create index ix_refunds_order_created on refunds(order_id,created_at desc);
''',
"mini-commerce/backend/src/test/java/com/example/minicommerce/order/domain/OrderEntityTest.java": r'''package com.example.minicommerce.order.domain;import static org.assertj.core.api.Assertions.*;import com.example.minicommerce.order.infrastructure.OrderEntity;import com.example.minicommerce.shared.error.BusinessException;import java.math.BigDecimal;import java.time.Instant;import java.util.UUID;import org.junit.jupiter.api.Test;class OrderEntityTest{private OrderEntity order(String n){return new OrderEntity(UUID.randomUUID(),n,1L,new BigDecimal("100"),BigDecimal.ZERO,new BigDecimal("100"),"JPY",null,Instant.parse("2026-01-01T00:00:00Z"));}@Test void cancelledOrder_cannotBePaid(){OrderEntity o=order("MC-X");o.cancel(Instant.parse("2026-01-01T00:00:01Z"));assertThatThrownBy(()->o.markPaid(UUID.randomUUID(),Instant.now())).isInstanceOf(BusinessException.class);}@Test void duplicateCancel_reportsNoSecondSideEffect(){OrderEntity o=order("MC-Y");assertThat(o.cancel(Instant.now())).isTrue();assertThat(o.cancel(Instant.now())).isFalse();assertThat(o.getStatus()).isEqualTo(OrderStatus.CANCELLED);}@Test void refundFailure_returnsPaidForSafeRetry(){OrderEntity o=order("MC-Z");o.markPaid(UUID.randomUUID(),Instant.now());o.requestRefund(Instant.now());o.refundFailed(Instant.now());assertThat(o.getStatus()).isEqualTo(OrderStatus.PAID);}}
'''
}
